### ISSUE TITLE
How to plot the RNAseqpipeline flowchart?

### ISSUE THREAD

**Issue by zhaoliang0302** [IARCbioinfo/RNAseq-nf#21]
Hi,
The flowchart of [RNAseqpipeline.png](https://github.com/IARCbioinfo/RNAseq-nf/blob/master/RNAseqpipeline.png) is pretty cool. Is it plotted with Adobe illustrator or other software? Thanks.

**Comment by nalcala** [comment]
Hi @zhaoliang0302 , 
Thanks! I did it by hand with inkscape (https://inkscape.org/), which is a free vector graphics software similar to illustrator. I highly recommend it, but you can also open it with illustrator. If you want to do one, you can start from the file in svg format at https://github.com/IARCbioinfo/template-nf [template-nf.svg](https://github.com/IARCbioinfo/template-nf/blob/master/template-nf.svg) , that you can open either with inkscape or illustrator, and duplicate/move things.

Cheers,

Nicolas

**Comment by zhaoliang0302** [comment]
Thank you so much for your reply!
